repo fix
Odinachi/flutterfire-ui-auth pull request #2
Opened 2022-07-04 11:05 UTC by Odinachi

2022-07-05 11:45 UTC, lesnitsky requested changes

2022-07-05 11:45 UTC, lesnitsky commented on lib/screens/home_screen.dart
> +            ));
trailing coma would make the formating a bit nicer

2022-07-05 11:45 UTC, lesnitsky commented on lib/screens/home_screen.dart
> +            return Center(
please move this to a separate screen

2022-07-05 13:05 UTC, Odinachi commented on lib/screens/home_screen.dart
> +            return Center(
alright.

2022-07-06 13:17 UTC, lesnitsky approved these changes

2022-07-07 06:53 UTC, merged